package org.mm0.kt

const val underscoreCS = "_"

internal const val COERCION = "coercion"
internal const val INFIXL = "infixl"
internal const val INFIXR = "infixr"
internal const val PREFIX = "prefix"
internal const val NOTATION = "notation"
internal const val PURE = "pure"
internal const val STRICT = "strict"
internal const val PROVABLE = "provable"
internal const val FREE = "free"
internal const val SORT = "sort"
internal const val TERM = "term"
internal const val DELIMITER = "delimiter"
internal const val DEFINITION = "def"
internal const val INPUT ="input"
internal const val OUTPUT ="output"
internal const val AXIOM = "axiom"
internal const val THEOREM = "theorem"
internal const val LOCAL = "local"
internal const val PUBLIC = "pub"
internal const val STRING = "string"
internal const val MAX = "max"
internal const val PREC = "prec"
internal const val LET = ":let"
internal const val CONVERSION = ":conv"
internal const val SYM = ":sym"
internal const val UNFOLDCONV = ":unfold"